// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS8zJgyQovJJ7jbZAUHsVEgXZiGvsmoLc',
    appId: '1:873543809700:web:cc9962daa05eaa19940431',
    messagingSenderId: '873543809700',
    projectId: 'appflutterhrm',
    authDomain: 'appflutterhrm.firebaseapp.com',
    storageBucket: 'appflutterhrm.firebasestorage.app',
    measurementId: 'G-CP2K4XVFME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwJWGOBJD-HIPuneJQd43CyWpQTcYi3Zc',
    appId: '1:873543809700:android:ce04961e0ec43367940431',
    messagingSenderId: '873543809700',
    projectId: 'appflutterhrm',
    storageBucket: 'appflutterhrm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTShhdsum2D7xs6w41gp_M3RqVJt0sZ_I',
    appId: '1:873543809700:ios:03b4be972178d30d940431',
    messagingSenderId: '873543809700',
    projectId: 'appflutterhrm',
    storageBucket: 'appflutterhrm.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationControle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTShhdsum2D7xs6w41gp_M3RqVJt0sZ_I',
    appId: '1:873543809700:ios:03b4be972178d30d940431',
    messagingSenderId: '873543809700',
    projectId: 'appflutterhrm',
    storageBucket: 'appflutterhrm.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationControle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS8zJgyQovJJ7jbZAUHsVEgXZiGvsmoLc',
    appId: '1:873543809700:web:0067da3f2593bf78940431',
    messagingSenderId: '873543809700',
    projectId: 'appflutterhrm',
    authDomain: 'appflutterhrm.firebaseapp.com',
    storageBucket: 'appflutterhrm.firebasestorage.app',
    measurementId: 'G-VJY3C77E9N',
  );
}
